### ISSUE TITLE
"Open source" doesn't mean what you think it means

### ISSUE THREAD

**Issue by MishaLarionov** [Coocla33/Samantha#25]
"Open source" means that someone can take and use your code, most of the time with a license. If you would like people to attribute you when they use your code, include an attribution license. Otherwise, make the repo private or use a different git service.

**Comment by Coocla33** [comment]
Thank you for the info! I will look into this tomorrow and get me a damn license! :D

**Comment by Coocla33** [comment]
Got the MIT License!
